apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-maven-app
  labels:
    app: simple-maven-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-maven-app
  template:
    metadata:
      labels:
        app: simple-maven-app
    spec:
      containers:
      - name: simple-maven-app
        image: aml51/my-image:latest 
        ports:
        - containerPort: 8080 
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
